# Generated by Django 2.2.9 on 2020-03-05 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200305_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='pregunta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Pregunta'),
        ),
    ]
