# Generated by Django 2.2.9 on 2020-03-05 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200305_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta', to='api.Encuesta'),
        ),
    ]
